version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - zip -r frontend.zip src/frontend
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - frontend.zip
